# Generated by Django 3.1.6 on 2021-10-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataGroup', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=40)),
                ('images', models.ImageField(blank=True, null=True, upload_to='bahro/mysite/static/img/')),
            ],
        ),
    ]
