# Generated by Django 3.1.6 on 2021-10-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='bahro/mysite/static/img/'),
        ),
    ]
