# Generated by Django 3.1.6 on 2021-10-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_insert_images2'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataGroup', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='insert',
            name='dataGroup',
        ),
        migrations.RemoveField(
            model_name='insert',
            name='images2',
        ),
        migrations.RemoveField(
            model_name='insert',
            name='project',
        ),
        migrations.AlterField(
            model_name='insert',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x000001EAF068F6A0>/'),
        ),
    ]
