# Generated by Django 3.1.6 on 2021-10-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211018_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x00000240AEF5E6A0>/'),
        ),
    ]
