# Generated by Django 3.1.6 on 2021-10-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211018_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert',
            name='NumbOfPics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insert',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
