# Generated by Django 3.1.6 on 2021-10-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211018_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insert',
            name='NumbOfPics',
        ),
        migrations.AddField(
            model_name='inserttext',
            name='NumbOfPics',
            field=models.IntegerField(default=0),
        ),
    ]
