# Generated by Django 3.1.6 on 2021-10-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211018_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='NumbOfPics',
        ),
    ]
