# Generated by Django 3.1.6 on 2021-11-14 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211029_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutTitles',
            new_name='AboutTitle',
        ),
    ]
