# Generated by Django 3.1.6 on 2021-12-01 03:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default=datetime.datetime(2021, 12, 1, 3, 5, 12, 389572, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
